version: '3'
services:
  
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mike
      MYSQL_DATABASE: instituto
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3309:3306
    volumes:
      - ./mysql:/var/lib/mysql
    


volumes:
  mysql:
